version: '3.9'

networks:
    shared:
        external: false

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - shared

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - shared
        restart: unless-stopped

    sphp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sphp
        command: "bash /app/deploy/scripts/run.sh"
        volumes:
            - ./:/app
        networks:
            - shared
        env_file: .env

    nginx:
        image: nginx:1.17.2
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./deploy/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
            - "./deploy/nginx/site.conf:/etc/nginx/conf.d/default.conf"
            - "./:/app"
        links:
            - sphp
        networks:
            - shared

volumes:
    pgadmin:
    postgres:
