version: '3'

networks:
    shared:
        external: false

services:
    starter_mysql_db:
        image: mariadb
        container_name: starter_mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_USER: $DB_USERNAME
            MYSQL_PASSWORD: $DB_PASSWORD
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - shared

    starter_pma:
        image: phpmyadmin/phpmyadmin
        container_name: starter_pma
        links:
            - starter_mysql_db
        environment:
            PMA_HOST: starter_mysql_db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            MAX_EXECUTION_TIME: 140000
        restart: always
        ports:
            - "$PMA_PORT:80"
        networks:
            - shared

    starter_php_backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: starter_php_backend
        command: "bash /app/deploy/scripts/run.sh"
        volumes:
            - ./:/app
        depends_on:
            - starter_mysql_db
        networks:
            - shared

    starter_nginx:
        image: nginx:1.14.2
        ports:
            - "$NGINX_PORT:80"
        volumes:
            - "./deploy/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
            - "./deploy/nginx/site.conf:/etc/nginx/conf.d/default.conf"
            - "./:/app"
        links:
            - starter_php_backend
        networks:
            - shared

volumes:
    dbdata:
