echo "current path is ${PWD}, starting execute run.sh";
echo "running composer";
composer install --working-dir=/app;
bash /app/deploy/wait_for.sh mysql_db:3306 -t 0 -s --;
echo "database is ready, running migration";
chown -R www-data:www-data /app;
echo "permissions set";
php /app/artisan migrate --force;
echo "starting supervisor";
service supervisor start;
echo "supervisor booted";
echo "running cron";
service cron start;
echo "cron running";
crontab -u www-data /app/deploy/cron/www-data;
echo "starting FPM";
php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.d/php-fpm.conf;
